/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _GameRoute } from '../pages/game';
import { Route as _IndexRoute } from '../pages/';
import { Route as _MatchingRoute } from '../pages/matching';
import { Route as _RankingRoute } from '../pages/ranking';
import { Route as _ResultRoute } from '../pages/result';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/game': (typeof _GameRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/matching': (typeof _MatchingRoute)['_inputType'];
    '/ranking': (typeof _RankingRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/game': (typeof _GameRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/matching': (typeof _MatchingRoute)['_outputType'];
    '/ranking': (typeof _RankingRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
  }
}
